### ISSUE TITLE
containerStyle and textStyle not working in iOS

### ISSUE THREAD

**Issue by johnylawrence1987** [expo/react-native-action-sheet#267] opened 2022-05-23 12:21 UTC
Hello,
I am able to customize the action sheet using the following properties: **containerStyle** and **textStyle**
But this is only applicable on Android, not iOS, any special reason? I would like to use the same style in both platforms

Thanks

**Comment by bradbyte** [comment] 2022-05-24 12:58
Hi @johnylawrence1987, when it comes to iOS, this package defers to the main ActionSheetIOS component, so there's no way to customize it outside of any parameters that Apple already allows. There has been a request before to allow for importing the Android version in iOS, which would solve your use case. I'll see how difficult that would be.

**Comment by bradbyte** [comment] 2022-10-12 18:20
Closing as a duplicate of #212.

**Closed by bradbyte** 2022-10-12 18:20 UTC
